version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Dushanbe
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Asia/Dushanbe
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
